### Health check
GET http://localhost:3001/status HTTP/1.1

### Create User
POST http://localhost:3001/users/create HTTP/1.1
content-type: application/json

{
    "fullname": "sample",
    "email" : "man@sample.com",
    "password": "securepassword"
}
